# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ci8KUJ4NkSzRU93C3Qiw7g0P2-T5hNaW
"""

import seaborn as sns
import matplotlib.pyplot as plt

data = sns.load_dataset("flights")

data = data.pivot("month","year","passengers")

#HEATMAP
sns.heatmap(data=data, annot=True, fmt="d", cmap="YlGnBu")

plt.show()

data.info

import seaborn as sns
import matplotlib.pyplot as plt

data = sns.load_dataset("flights")

sns.lineplot(data=data, x="year", y= "passengers")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

data = sns.load_dataset("iris")

sns.swarmplot(x="species",y="petal_length", data=data)

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

data = sns.load_dataset("titanic")

sns.countplot(data=data, x="class")


plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

data= sns.load_dataset("tips")
#SCATTER
sns.scatterplot(data=data, x="total_bill",y="tip")
plt.show()